### PR TITLE
improves simple Eady example

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by glwagner** [comment]
Much better.

I'm also struggling with good parameters for this problem. Do you have any suggestions?

**Comment by navidcy** [comment]
not on top of my head...
what's happening at iteration `i=250`?!
the fields look very weird then

**Comment by navidcy** [comment]
> I'm also struggling with good parameters for this problem. Do you have any suggestions?

perhaps @oliasselin has suggestions for good set of parameters for Eady problem?

**Comment by oliasselin** [comment]
Actually I might! I am currently working on a paper (attached draft) on the
interaction between NIWs and a 'realistic' QG flow generated by an Eady
model (although with non-uniform N). I had trouble choosing parameters too
back then. In 'eady_details' I describe the model and give the parameters I
ended up choosing.

One thing I realized is that if your resulting turbulent flow is
surface-confined (which was my case since the realistic stratification
profile I use is also surface confined, see fig 1 of the draft) then the
perturbations grow much stronger than the original mean-flow. That must be
because the Ekman dissipation of the barotropic mode is not very effective.
This would probably be less of a problem on the beta-plane... anyway.

I hope this helps
Cheers
Olivier

PS: Greg, while at it, have you given some thought to the correspondence
between the XV Lagragian-mean transfer terms and their Eulerian-mean
counterparts (the horizontal and vertical shear production terms everybody
else in the world cares about)? I am trying to work this out now but it is
not as trivial as I thought...

**Comment by glwagner** [comment]
@oliasselin you shouldn't worry so much about what everyone else in the world cares about!

Just kidding, that sounds interesting. I'd love to hear your thoughts. As a matter of fact I am in San Diego right now, but leaving tomorrow. I will be back at the end of the month, however, so we could meet up then if you want.

Thanks a lot for your thoughts about the Eady problem. Have you tried to reproduce your QG results in a Boussinesq model? Is that possible? We could explore that in this repository, for example.

**Comment by oliasselin** [comment]
Hey Greg!

I'm actually returning to SD tomorrow evening from Edinburgh (collaborating
with J. Vanneste)... Do let me know when you come back!

I haven't run the Eady-NIW sims in my Boussinesq model yet, but that's part
of the ultimate plan. That's a bit why I wanted to sort out the
Lagrangian-Eulerian correspondence first. But I think I'm basically there.
Stay tuned!

**Pull request merged**
